---

- name: check if dhcpd dir exists
  stat:
    path: "{{ dhcpd_dir }}"
  register: dhcpd_dir_stat

- name: create dhcpd dir
  block:
    - name: check if parent is zfs dataset
      shell: zfs list | grep '\s{{ dhcpd_dir | dirname }}$' | cut -d ' ' -f1
      register: parent_dataset
      changed_when: False

    - name: create dhcpd_dir dataset
      zfs:
        name: "{{ parent_dataset.stdout }}/{{ dhcpd_dir | basename }}"
        state: present
        extra_zfs_properties:
          compression: "lz4"
      when: parent_dataset.rc == 0

    - name: create dhcpd_dir directory
      file:
        path: "{{ dhcpd_dir }}"
        state: directory
      when: parent_dataset.rc != 0

    - name: create dhcpd_dir var directory
      file:
        path: "{{ dhcpd_dir }}/var"
        state: directory
        owner: "{{ dhcpd_user }}"
        mode: '0750'

- name: set dhcpd_dir permission
  file:
    path: "{{ dhcpd_dir }}"
    owner: root
    group: root
    mode: '0755'
