---

# find interface
# find subnet
# find gateway

- name: set dhcpd_conf
  set_fact:
    dhcpd_conf: "{{ dhcpd_dir }}/dhcpd.conf"

- name: check if dhcpd_conf exists
  stat:
    path: "{{ dhcpd_conf }}"
  register: dhcpd_conf_stat

- template:
    src: dhcpd.conf
    dest: "{{ dhcpd_conf }}"
    owner: root
    group: root
    mode: '0755'
  when: dhcpd_conf_stat.stat.exists == false

# lease file in var
# lease file right
#             

