---

- name: debconf for dhdcpd relay
  debconf:
    name: 'isc-dhcp-relay'
    question: 'isc-dhcp-relay/{{ item.key }}'
    vtype: 'string'
    value: '{{ item.value }}'
  with_dict:
    servers:    '{{ dhcpd_relay_servers | join(" ") }}'
    interfaces: '{{ dhcpd_relay_interfaces | join(" ") }}'
    options:    '{{ dhcpd_relay_options }}'
  register: dhcpd_register_relay_debconf
  when:
    - ansible_os_family == "Debian"
    - dhcpd_mode == 'relay'

- name: install dhcpd packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ dhcpd_packages[dhcpd_mode] }}'
    - '{{ dhcpd_packages["extra"] }}'
  register: install
  when:
    - dhcpd_mode == 'server' or dhcpd_mode == 'relay'

- name: Reconfigure ISC DHCP relay
  command: dpkg-reconfigure --frontend=noninteractive isc-dhcp-relay
  notify: [ 'Restart dhcp relay' ]
  when:
    - ansible_os_family == "Debian"
    - dhcpd_register_relay_debconf|d() and dhcpd_register_relay_debconf.changed

- name: disable default service
  service:
    name: '{{ dhcpd_default_service[dhcpd_mode] }}'
    enabled: no
    state: stopped
  when: install is defined and install.changed
