---

- block:
    - include_tasks: context.yml

    - include_tasks: install.yml

    - include_tasks: configure.yml

  when: want_dhcpd

- name: "set has_dhcpd to {{ want_dhcpd }}"
  set_fact:
    has_dhcpd: "{{ want_dhcpd }}"
