#!/bin/sh

DHCPD_CONF="{{ dhcpd_conf_file }}"
DHCPD_LEASE="{{ dhcpd_lease_file }}"
DHCPD_PID="{{ dhcpd_pid_file }}"
DHCPD_USER="{{ dhcpd_user }}"
INTERFACES="{{ dhcpd_interface }}"

exec dhcpd \
     -q \
     -f \
     -cf "$DHCPD_CONF" \
     -lf "$DHCPD_LEASE" \
     -pf "$DHCPD_PID" \
     -user "$DHCPD_USER" \
     $INTERFACES \
     2>&1
