#!/bin/sh

SCRIPT_PATH=$(cd "${1%/*}"; pwd)

DHCPD_CONF="{{ dhcpd_conf_file }}"
DHCPD_LEASE="{{ dhcpd_lease_file }}"
DHCPD_PID="{{ dhcpd_pid_file }}"
INTERFACES="{{ dhcpd_interface }}"

exec dhcpd \
     -q \
     -f \
     -cf "$DHCPD_CONF" \
     -lf "$DHCPD_LEASE" \
     -pf "$DHCPD_PID" \
     -user "{{ dhcpd_user }}" \
     $INTERFACES \
     2>&1
